### ISSUE TITLE
Use Second Camera

### ISSUE THREAD

**Issue by Sixeck** [serratus/quaggaJS#10]
How is it possible to change to a (possible) second Camera ? Like Tablets and Mobil Phones... 
This programm is using the front camera

**Comment by serratus** [comment]
I assume you are using Chrome, correct? Because in Firefox you can select the camera every time the browser asks for camera access. However, in Chrome the back-facing camera should be automatically selected, as it does on my Galaxy S2 and Nexus 5. See https://github.com/serratus/quaggaJS/blob/master/src/camera_access.js#L69 for details.

**Comment by MC3Arc** [comment]
Yes, i'm using chrome on my galaxy s3, but somehow it doesnt work with 'environment'.. But i found a solution, i i'm using the exact camera ID number and now its working with the rear camera.. thanks for your fast answer

**Comment by serratus** [comment]
I see, so you are simply using the lastest source found. However, I'm still wondering what your browser returns for the `facing` property of each source. Would it be possible for you to log the `facing` attribute during the iteration like `console.log(sourceInfo.facing);`?

**Comment by Lucky698** [comment]
To implement this quaggajs in tablet what are the specifications required for camera.

**Comment by serratus** [comment]
What exactly do you want to achieve? Do you want the rear-facing (``environment``) or user-facing (``user``) camera to be used? There is a config you can pass in during initialization:
``````javascript
Quagga.init({
    inputStream: {
        type: "LiveStream",
        constraints: {
            width: 640,
            height: 480,
            facing: "environment" // or user
        }
    },
}, function() {
    Quagga.start();
});
``````

**Comment by Lucky698** [comment]
What camera resolution needed to detect the barcode?

**Comment by serratus** [comment]
Usually, 640 x 480px should be sufficient. But it depends on the autofocus capabilities of your camera. Have you tried playing around with the [examples](http://serratus.github.io/quaggaJS/examples/live_w_locator.html)?

**Comment by Lucky698** [comment]
Thanq

**Comment by Lucky698** [comment]
If the camera doesn't have auto focus feature it won't work.

**Comment by serratus** [comment]
That's not entirely true. If the barcodes are big enough and the distance to the camera is not too close, it should still work in some situations. But you are right, auto-focus definitely improves the recognition.

**Comment by Lucky698** [comment]
Model No.: Softwinerkf026
Android Version 4.0.4
Baseband version 1.5rc3
Kernel version 3.0.8+
Build No.: HJKF026_dbl0308-09-121D_V1.1.12_130520_30LKGU_m805_cceb172

This is my tablet configuration which don't have auto-focus feature.When I tested in the tab in Opera browser,the rear camera is not displaying the video,can you please suggest us a solution for this,will quaggaJS works well on Opera browser with the above configuration? I am unable to identify the exact reason.Please suggest us a solution for this.

**Comment by serratus** [comment]
I was not aware that you were using the Opera browser. Unfortunately, I haven't tested the recent versions in Opera yet. That's why I don't have more info for you right now. I'll come back to you whenever I have the time to test it on Opera.

Does your tablet have a front & back-facing camera? I could not find much information. As it seems, the camera has only a 640 x 480 px camera with rather poor camera capabilities. The barcode-localization feature might suffer from that, because it needs auto-focus for that. The decoding feature could work, but I don't have an example yet online.

**Comment by Lucky698** [comment]
Yes,Tablet has front&back facing camera.But when I tried to capture video using back facing camera, video displayed in green area with some horizontal,vertical lines.Again I tried with front-facing camera video displayed but it was very slow,barcode localization not happening.

I tested in "Chromium browser", browser invoked back camera by default,here also  video displayed in green area with some horizontal,vertical lines.

I tested in "Firefox browser",browser invoked front camera by default,here also video displayed but it was very slow,barcode localization not happening.

 Finally I am not understanding  problem exactly.Could please suggest alternatives to this.I should scan barcode using back facing camera in web application.

**Comment by serratus** [comment]
The problem with the camera seems to be related to #27 right? Does the camera image look like the image depicted in the linked issue? I'll try to investigate this issue in more detail. The only problem I'm having is, that all the Android devices I own have no problems with the camera.

You have also mentioned how slow the video is displaying. This is actually a performance problem which is caused primarily by your tablet's CPU. It is a single-core ARM processor with 1GHz which is a little underpowered for real-time image processing on the web. I suggest, since it only offers a single-core CPU, to set the ``numOfWorkers`` to ``1`` which should improve the overall performance.

The only remaining problem seems to be the auto-focus issue. This might be solved if we get the rear camera to work. Otherwise, it's simply a software issue so that the browser (Chrome & Firefox) cannot trigger the auto-focus correctly (happens to be on my Samsung Galaxy S2).

**Comment by Lucky698** [comment]
Thank You.I will test it.

**Comment by wisnunue** [comment]
how to change config camera if im using ip camera.tks ^_^

**Comment by NiveditaParker** [comment]
I am using the dist/quagga.min.js script tag to read the barcode in angular js. It works perfectly when I upload the image but for the same image with barcode if I take a picture in my camera, I get the output as unable to read. please help!

**Comment by LouysPatriceBessette** [comment]
This issue was closed long time ago without real good solution.
I also encountered the issue and found a better walk-around than what @ghost posted on jan 11, 2015 (see above).

The trick is to find the back camera ID in order to provide it to Quagga using `deviceId` instead of the `facingMode` option.

    if (!navigator.mediaDevices || !navigator.mediaDevices.enumerateDevices) {
      alert("enumerateDevices() not supported.");
      return;
    }

    var backCamID;

    navigator.mediaDevices.enumerateDevices()
    .then(function(devices) {
      devices.forEach(function(device) {
        //alert( JSON.stringify(device) );
        if( device.kind == "videoinput" && device.label.match(/back/) != null ){
          //alert("Back found!");
          backCamID = device.deviceId;
        }
      });
    })
    .catch(function(err) {
      //alert(err.name + ": " + err.message);
    });

    if(typeof(backCamID)=="undefined"){
      console.log("back camera not found.");
    }

Then in Quagga init:

    Quagga.init({
      inputStream: {
        type : "LiveStream",
        constraints: {
          width: {min: 640},
          height: {min: 480},
          aspectRatio: {min: 1, max: 100},
          //facingMode: "environment" // or user
          deviceId: backCamID
        }
      }
      //...
    });

I've look around the Quagga code to find where this `facingMode` was compared... And gave up.
That just looks like a whole in the code.

I used Quagga 0.12.1 which still is the latest available CDN here: https://cdnjs.com/libraries/quagga

**Comment by michi927** [comment]
I am using the script tag quagga.js.
I take the deviceID from the back Cam of my phone. 
But if I set the deviceID = backCamID like @LouysPatriceBessette it is no difference to setting 
deviceID = frontCamID (frontCamID although get by the function from @LouysPatriceBessette).
 
This is my Quagga.init:

            Quagga.init({
            inputStream : {
            name : "Live",
            type : "LiveStream",
            constraints: {
            width: {min: 640},
            height: {min: 480},
            aspectRatio: {min: 1, max: 100},
            //facingMode: "environment" // or user
            deviceId: backCamID
            },
            target: document.querySelector('#camera')    // Or '#yourElement' (optional)
            },
            decoder : {
            readers : ["code_128_reader","ean_reader","ean_8_reader"]
            }
        }, function(err) {
            if (err) {
                console.log(err);
                return
            }
            console.log("Initialization finished. Ready to start");
            Quagga.start();
        });

Please help!

**Comment by ericblade** [comment]
1st, do NOT request an aspectRatio max 100, 2 should be sufficient.  iOS will actually try to give you a 100 aspect ratio, which doesn't work well at all.

My guess would be that you're not actually supplying the correct camera id, so it's just using whatever it finds first.  

The function provided above from @LouysPatriceBessette would not work on any phone device I've seen, as none of the ones I've used actually provide a label saying which camera it is.  Not to say it won't work on some, but it definitely wouldn't work on the ones I've seen.  The ones that I've seen, the only way to verify that the camera is the one that is wanted, is to ask the user which one they want to use (or, I guess, you could build a dictionary of deviceIds to look it up in, but that seems excessive)

**Comment by michi927** [comment]
Thank you for you quick answer.
I don´t think that I have the false camera id. Because while USB Debugging with my phone I saw both cameras with there IDs and there was the right Id in the var backCamID.

What do you mean with ask the user which one they want to use? 
There is the same tag deviceId I set to the cameraID, isn´t it?

**Comment by ericblade** [comment]
well, in my app, i present the user a choice of which camera to use, then i save that deviceid, and use it at startup afterwards.  

i don't see anything incorrect about your code, so i would log the device ids returned by Quagga.enumerateVideoDevices() and make sure you are using the one you think you're using.

**Comment by YusufKinis** [comment]
5

**Comment by YusufKinis** [comment]
Yardım edin 1 haftadır uğraşıyorum beceremedim. Arka kameraya geçemiyorum.
------------------------------------------------------------------------------------------
quagga_init: function(set_defaults, resolution_width, resolution_height) {
        var camera_id = undefined
        Quagga.CameraAccess.enumerateVideoDevices().then(function(cameras) {
            camera_id = cameras[cameras.length - 1]["deviceId"]
        })
        Quagga.init({
                inputStream: {
                    facingMode: "environment",
                    name: "Live",
                    type: "LiveStream",
                    target: document.querySelector('#quagga'),
                    constraints: {
                        facingMode: "enviroment",
                        deviceId: camera_id,
                        width: {
                            min: resolution_width
                        },
                        height: {
                            min: resolution_height
                        }

                    }
                },
                decoder: {
                    readers: [{
                        format: "code_128_reader",
                        config: {}
                    }, {
                        format: "ean_reader",
                        config: {}
                    }, {
                        format: "code_39_reader",
                        config: {}
                    }, {
                        format: "code_93_reader",
                        config: {}
                    }, {
                        format: "ean_8_reader",
                        config: {}
                    }, {
                        format: "codabar_reader",
                        config: {}
                    }, {
                        format: "upc_reader",
                        config: {}
                    }]
                },
                locate: true,
                showCanvas: true,
                showPatches: true,
                showFoundPatches: true,
                showSkeleton: true,
                showLabels: true,
                showPatchLabels: true,
                showRemainingPatchLabels: true,
                boxFromPatches: {
                    showTransformed: true,
                    showTransformedBox: true,
                    showBB: true
                }
            },

            function(err) {
                if (err) {
                    console.log(err);
                    return
                }
                console.log("Quagga initialization finished. Ready to start");
                Quagga.start();
                if (set_defaults) {
                    track = Quagga.CameraAccess.getActiveTrack()
                    setTimeout(this.get_capabilities_and_restart, 2000)
                } else {
                    this.set_zoom()
                }
            });
    },
