### ISSUE TITLE
how about the barcode with large gaps

### ISSUE THREAD

**Issue by codercheng** [serratus/quaggaJS#11]
how to locate the barcode with large gaps , such as, RSS14..., a large whitespace between two black bars.  
you said:
```
First of all, cells containing no, or just one component are discarded immediatelly and are not used for further processing.
```
but,   one component may be the bar...

**Comment by serratus** [comment]
Good question. When implementing the barcode-locator part, my initial goal was to get it working with Code128 barcodes. All the parameters you can find in the source are determined empirically by simply checking which work best. It might be a good idea to create a test-set of possible barcodes and then experiment with the parameters to find the best fit (machine learning?).

However, you can try to increase the _patch_ size so that at least two components can fit into each patch. Depending on the distance to your camera and the _whitespace_ around the barcode, this could actually work. Otherwise, try to alter the conditions in a way that they fit into your equation.

Hope that helps.
