### ISSUE TITLE
CODE 93 barcode support in Quagga JS[enhancement]

### ISSUE THREAD

**Issue by sidheshnalawade** [serratus/quaggaJS#110]
Hey can we accommodate CODE 93 barcode scanning support in Quagga JS as enhancement in this plugin , because its the best plugin which i have found so far with great accuracy rate.

**Comment by serratus** [comment]
I'll put this request on my list. It doesn't seem to take to much effort to implement this kind of barcode-decoding. You will be notified as soon as I start implementing this type.

Since you are asking for support: Do you have a few samples on hand? Images from you camera? Mobile phone? Or even a video?

**Comment by dreamweiver** [comment]
@serratus , i just checked your plugin, its cool :+1:  like other users of your plugin, even i 'm eager to know when code 93 decoding would be out.

**Comment by ericblade** [comment]
@sidheshnalawade @dreamweiver it seems that there has been Code 93 support (code_93_reader.js) since at least May of 2017, can we go ahead and close this task, or is there something remaining to be done here?

**Comment by ericblade** [comment]
Thanks!
