### ISSUE TITLE
UPC-E codes never return codeResult.code 

### ISSUE THREAD

**Issue by nikkwong** [serratus/quaggaJS#112]
Is this intended? I have never gotten a code result from a UPC-E barcode. I'm only getting results in the ```boxes``` property. 

Willing to fix with a pull request if it is helpful. 

Note that I am only using ```decodeSingle```.

**Comment by serratus** [comment]
What does your configuration look like? I've just tried with my Samsung Galaxy S6 and it worked. The `decodeSingle` method is not very optimized for that use-case since it's only got one chance to decode the picture. This should definitely be improved in the future by trying multiple resolutions/presets at once.

Here's my try: 
![screenshot_2016-06-08-21-29-40](https://cloud.githubusercontent.com/assets/1381822/15908178/9b1c93f2-2dc0-11e6-9794-97d6e61b4566.png)

**Comment by nikkwong** [comment]
Great job on the lib, I'll close the issue.
