### ISSUE TITLE
Minification causes JavaScript SyntaxError

### ISSUE THREAD

**Issue by PLPeeters** [serratus/quaggaJS#15]
For some reason, the code doesn't work anymore when minified, which is a bummer since it's almost three times smaller that way. The JavaScript error I'm getting is "Uncaught SyntaxError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL 'undefined' is invalid.". The error originates from the `blob` worker URL.

I'm getting this error 4 times, which seems to be one time per worker, given it launches 4 workers when I use the non-minified version.

**Comment by serratus** [comment]
Thanks for pointing out that issue. I've updated the README file to include a section about the minification process. See 3c4a108a4adcce5a591335cdbaae371a5abd4f9c or [README](https://github.com/serratus/quaggaJS#installation)

Basically, what you have to do is, change the config so that `config.scriptName` matches the filename of your minified code.

**Comment by PLPeeters** [comment]
Thanks for the clarification, that fixed it.
