### ISSUE TITLE
Images not decoding

### ISSUE THREAD

**Issue by tcole6** [serratus/quaggaJS#163]
I have a few barcode images that are not decoding for me. I have attached them below:
EAN-8
![ean8](https://cloud.githubusercontent.com/assets/2567023/23079265/2e757486-f51a-11e6-9e56-6178291c7899.png)
UPC-E
![upc_e](https://cloud.githubusercontent.com/assets/2567023/23079276/3df168fc-f51a-11e6-8bc5-892d3d8ab9fc.png)
Industrial 2 of 5
![industrial-2-0f-5](https://cloud.githubusercontent.com/assets/2567023/23079316/6624a8a2-f51a-11e6-8a2d-c23a1ce08a2f.jpg)

I still have some work to do getting the video deed to work, but I understand that to use fromVideo I may need https?

**Comment by serratus** [comment]
Yes, you are right. You need `https` if you don't use `localhost`.

I've just tried your examples, and the UPC-E and EAN-8 versions work just fine. The problem is the whitespace and the size of the barcode in case you are using the `file` method. Try capturing them using your phone pointed to your monitor. That's how I just tried.

And the problem with the Industrial 2 of 5 is, that it is not supported. You might confuse it with ITF, (I2of5 or Interleaved 2 of 5).
