### ISSUE TITLE
Cannot install from npm registry?

### ISSUE THREAD

**Issue by bcho** [serratus/quaggaJS#17]
I can't find the `quagga` package in npm registry, why don't you register this package on the registry?

**Comment by serratus** [comment]
Haven't really though about it, thanks for pointing that out.

**Comment by serratus** [comment]
I started preparing the repository for publishing it on npm. You can take a look at the branch from this commit 8bc119b62e136e7e1d398d402dec9fcc9e60a1f4. But there is still a problem I don't know how to fix. Since quaggaJS runs with multiple web-workers as default, the filename, as well as the global object must be known in advance. Currently, I get around this issue by configuring the filename in the [config.js](https://github.com/serratus/quaggaJS/blob/master/src/config.js) file and assuming a global object named Quagga (see [start.frag](https://github.com/serratus/quaggaJS/blob/master/build/start.frag)).

Any ideas how to get around that and create a clean module for npm?

**Comment by serratus** [comment]
From now on, you can install quagga via npm and use it within browserify, or webpack.
