### ISSUE TITLE
Is the library still maintained?

### ISSUE THREAD

**Issue by jpsfs** [serratus/quaggaJS#291]
Hi!

This project seems very interesting but seems to be stale for a while.
Is someone still maintaining it?

Best,
José

**Comment by TomasHubelbauer** [comment]
I hope it is, but if not, it would help to [archive the GitHub project](https://help.github.com/articles/archiving-a-github-repository/) so people do not have to wonder.

**Comment by ericblade** [comment]
It seems that serratus has completely disappeared. I hope he's OK.  I would offer to take up the reins on it, if people have updates that they want to pull in, i'd be happy to setup a fork and take pulls and such.  I'm not much on knowledge as to how this all works, though.

**Comment by TomasHubelbauer** [comment]
I have contacted @serratus on his email in his profile. I'll update the thread if he responds. If not, I think a fork is a good idea.

**Comment by ericblade** [comment]
i meant to say that i don't know much about how quagga works.  I'm perfectly fine at managing github repos, but i have never studied quagga beyond determining how the basic configuration options work.  i'd be happy to manage a fork though, since this is currently a cornerstone of a project i'm working on, and i'd definitely like to see it get improvements, preferably to a central location.

with 416 other forks out there, it's got to be hell trying to figure out who's made changes out there, and if they are good or not.  (anyone know of any tools to make that easier?)

**Comment by kristate** [comment]
Setup a repository here for everyone's patches:
https://github.com/NeraiCorp/getUserBarcode

**Comment by serratus** [comment]
Please leave a comment in #300 if you are interested in becoming a maintainer
