### ISSUE TITLE
Fail with the HTML5 File API to decode a pre-taken image

### ISSUE THREAD

**Issue by devnev0** [serratus/quaggaJS#30]
If I take a barcode photo  with a Moto G 4G, I have any result. When I try with the same image (taken with this phone) on a pc, I view this error:
"Error: Image dimensions do not comply with the current settings: Width (449.38271604938274 )and height (800) must a multiple of 1
http://localhost:8383/OnMyShelves/js/libs/serratus/quagga.min.js
Line 9"

Firstly, I think the image file is corrupted but it works fin with other decode Library.

**Comment by serratus** [comment]
Thanks for reporting! The main problem is, that the image has really odd dimensions. Can you tell me the original resolution of the file? It seems like the aspect ratio is 16:9, but missing one or two pixels. That's definitely something I have to address, so that QuaggaJS can work with all images, regardless of the size.

I'll try to come up with a solution. In the meantime, can you post the image and/or its dimensions?

**Comment by devnev0** [comment]
Yes, it 'll be easier for you with the image:
![img_20150505_105109950](https://cloud.githubusercontent.com/assets/12231936/7470256/97596b36-f31b-11e4-8e43-28c612d707e5.jpg)

**Comment by serratus** [comment]
Thanks a lot for the image. The dimensions are really odd (1.456px × 2.592px) and that's why it does not work with the current implementation. I hope to get around this limitation in the next few days. Basically, your image is not even real 16:9 aspect ratio, and I have to find a way to accept all dimensions, regardless of aspect ratio and internal needs.

**Comment by devnev0** [comment]
Yes it's very odd.
Thanks you very much.

**Comment by jamsshhayd** [comment]
was this issue fixed?
