### ISSUE TITLE
Why does not it work on ios (safari or chrome)? Test in iOS 11.3

### ISSUE THREAD

**Issue by jcarloscarrion** [serratus/quaggaJS#308]
In android work perfectly, but in iphone (safari or chrome) it does not work. It appears as in the following image attached:

![imagen](https://user-images.githubusercontent.com/40891412/42379260-70562588-812a-11e8-893e-c3e32c76f4c3.png)

I hope someone has some solution, Thanks.

**Comment by ericblade** [comment]
I suspect that the browser console may provide some clues / answers, but a screen cap of a blank screen isn't really going to give us much to go on :)

**Comment by jcarloscarrion** [comment]
I debug the page in mobile, and the error that appears in the console is:

![imagen](https://user-images.githubusercontent.com/40891412/42456643-b73a0fec-8395-11e8-8c86-105e0ab863fe.png)

I don't know what the problem might be.

**Comment by ericblade** [comment]
As far as I'm aware, Chrome on iOS cannot support getUserMedia, but in Safari, my first thought is that Safari may not have camera access enabled, so maybe it disables the entire getUserMedia ? not sure.  what version of iOS?

**Comment by jcarloscarrion** [comment]
The device on which I performed the tests to see the console browser was an iOS10. I think that's why the problem is getuserMedia. In iOS 11.3 have the same problem but I have no way to access the browser console in iOS 11.3, it does not appear the device in iMAC in the developer tab to debug :(

**Comment by jcarloscarrion** [comment]
In the web of example (https://serratus.github.io/quaggaJS/examples/live_w_locator.html) with an iOS 11.3 device does not work either, I have tried on 2 different devices and I see the same error as in the first image I attached. 
Does it work for you with a ios device the web of example?

**Comment by ericblade** [comment]
I don't have an iOS device to test on, but yes, older versions of iOS do not have working getUserMedia, I'm not sure when it's supported from exactly.  There are several issue tickets here where people have reported it working in iOS 11, and I think at least some point releases of 10.  I do need to get an iOS thing to check with, as my application doesn't even show *anything* in iOS, and I need to figure out what the reason is for that :-S

**Comment by getsalty** [comment]
Hey, a few helpful comments:

getUserMedia is only available for iOS 11+ so you will always get an error on the iOS 10 device that you are reading the console output on. 

also, I have just tested that example you provided (live_w_locator) on 2 devices:
iOS 11.4  Iphone 7 plus
iOS 11.4  ipod mini

both devices can use the example and read barcodes

**Comment by jcarloscarrion** [comment]
Ok, I'll try to update the devices to 11.4. Because in 11.3 the example of live_w_locator is not working for me.

**Comment by noobling** [comment]
Yeah for some reason I am sometimes not prompted to "allow camera access" so it doesn't work using iphone 6 on ios 11.4 safari.

**Comment by leducson** [comment]
It works on ios with the condition that your website is https

**Comment by philip556677** [comment]
@leducson Is there any explanation of why they'd want to do it this way? ( strictly https)
I seem to be running into that issue myself.

**Comment by UncleSamSwiss** [comment]
@bigbob556677 more and more web APIs are limited to HTTPS (see https://caniuse.com for some examples). Basically: Apple doesn't want you to send images captured through the user's camera over an unencrypted connection. Yes, I know in the case of this library it doesn't make sense since we are not sending the image anywhere, but how should the browser know about that?

**Comment by ericblade** [comment]
I think we've fairly well shown that the library does work in iOS, so I'm going to close this and other "doesn't work in iOS" reports.
