### ISSUE TITLE
Leading zero added/deleted between EAN13 and UPCA

### ISSUE THREAD

**Issue by thaibinh1909** [serratus/quaggaJS#342]
Hi,
I'm mixing EAN and UPC, quagga automatically adds and removes a leading 0 in my case.
I want it to return original value without conversion. Is it possible?

For example:

If I config like below, I get EAN13 missing leading zero. **0**123456789012 -> 123456789012 
`readers: [ "upc_reader", "ean_8_reader", "upc_e_reader", "ean_reader" ]`
In the console, my barcode is recognized as UPC_A.

On the other hand, below config gives UPCA with additional leading zero. 123456789012 -> **0**123456789012
`readers: [ "ean_reader",	"ean_8_reader", "upc_e_reader", "upc_reader"]`
In the console, my barcode is recognized as EAN_13.

In what order I can get the original result?
Thank you very much. You created a great library.

**Comment by ericblade** [comment]
I'm a bit confused. UPC is a 12-digit, and converts to a EAN by adding a 0.

Can you be specific about what the barcode you're trying to scan is, and what is happening?

It would seem that if you've got upc reader first, then ean reader, and you try to scan a ean, you're going to end up with the upc portion of it, since EAN and UPC are virtually identical.  I'm not even sure that this *can* be resolved, as one is a subset of the other.

**Comment by thaibinh1909** [comment]
> It would seem that if you've got upc reader first, then ean reader, and you try to scan a ean, you're going to end up with the upc portion of it, since EAN and UPC are virtually identical. I'm not even sure that this _can_ be resolved, as one is a subset of the other.

Yes, after some search, I understood how UPC and EAN are going along. So I decided to remove `"upc_reader"` and handle the leading zero by myself. So far so good.
