### ISSUE TITLE
Is there any option to prevent initialisation of the drawingBuffer canvas ?

### ISSUE THREAD

**Issue by ivanelrey** [serratus/quaggaJS#349]
To avoid displaying of the canvas I use the below code, but the canvas is still being initialised and it disappears immediately but it is still noticeable.

```
Quagga.init(this.state, function(err) {
  const drawingCanvas = Quagga.canvas.dom.overlay;
  drawingCanvas.style.display = 'none';
  ...
  Quagga.start();
```

Is there any way to not use the canvas at all?

**Comment by valoricDe** [comment]
I wonder what the canvas is used for. Browsers that don't support the video element?

**Comment by ericblade** [comment]
i haven't taken the time to determine if it can be removed, got much larger things on my plate, but it's at least useful for drawing things such as an indicator of where the scanning area is or intermediate for final results of a scan...

haven't looked to see if it can be removed safely, since it's existence doesn't seem to be a problem

**Comment by valoricDe** [comment]
Ah ok thank you for clarification. So I guess I rather go with absolute positioning to see it. And for all others your first comment should suffice I guess
