### ISSUE TITLE
Multiple Readers options in live stream example

### ISSUE THREAD

**Issue by RajuIO** [serratus/quaggaJS#352]
I want to read different types of barcodes by scanning through a live webcam.

But every time I need to specify the reader type to read a particular type of barcode.

and one more issue is I don't know, which type of barcode, I am scanning.so it is not throwing any error or message saying that it is not a valid barcode reader type.

Is there any method, which can be used to add all types of readers at a time and scan the barcodes without specifying the barcode reader type 
or
 by default, it can detect and show the result based on the barcode type which I am scanning.

**Comment by ericblade** [comment]
Reader is specified as an array of reader modules to use.  You can specify as many or as few as you need.  The problem with that, is that many barcode formats are extremely similar to each other -- for example, a ISBN13, a UPC, and a EAN are basically the same barcodes, with varying numbers of digits.  If you enable some of those in combinations, you'll end up defeating the purpose, as you'll be getting invalid results as one reader picks up part of the barcode, and sends in a successful scan, so the other readers don't get a chance to look at it (basically).

Ultimately, your application should be limited to reading only the specific set of barcodes that it will need to read -- enabling all of the readers just drains cpu and creates confusion when one reader triggers a good read, but it's not the actual result you wanted.

Best advice is to know what you need to read, and only enable the readers for those specific things.  And do it in the order of largest code to smallest code (ie, EAN, then UPC, since UPC is a subset of EAN)

**Comment by RajuIO** [comment]
thanks for your advice, we will do accordingly
