### ISSUE TITLE
_inputStream.setWidth is not a function

### ISSUE THREAD

**Issue by elsigh** [serratus/quaggaJS#37]
Sometimes I get the following with 'x-large' for my patchsize
640px x 160px
Uncaught TypeError: _inputStream.setWidth is not a functioncheckImageConstraints @ admin_bundle.js:75641canRecord @ admin_bundle.js:75657that.trigger @ admin_bundle.js:68945(anonymous function) @ admin_bundle.js:75613checkVideo @ admin_bundle.js:75406loadedData @ admin_bundle.js:75415

**Comment by serratus** [comment]
The problem seems to be setting the video-size after checking it's constraints according to the patch-size. Since the patch-size is strictly square, the input-image has to be modified to fit into that grid. I haven't tested the aspect-ratio code of yours thoroughly enough, but ``x-large`` setting with an aspect ratio of 4 does not work correctly with video input. This is because the video-stream does not yet have ``setWidth`` method of the ``ImageStream``. I'll try to fix that in the afternoon. Thanks for pointing that out!
