### ISSUE TITLE
 Huawei mobile phone calls front camera

### ISSUE THREAD

**Issue by StarTianYang** [serratus/quaggaJS#403]
When using quagga.js, the front camera will be called in Huawei mobile phone. How can I solve this problem?

**Comment by ericblade** [comment]
You'll need to use https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices which you can access via Quagga.CameraAccess.enumerateVideoDevices() .. get the deviceId for the device you want to use, and then use that in your constraints rather than facingMode

The "live_w_locator" sample has demonstration code to do this sort of thing, also
https://github.com/ericblade/quagga2/blob/master/example/live_w_locator.js#L85
