### ISSUE TITLE
Note10 S20 - New phones with multiple cameras

### ISSUE THREAD

**Issue by berberon** [serratus/quaggaJS#435]
Seems like there is a problem with the new multicamera phones.
On the "old" phones everything is perfect... on the new ones I can only guess, the wrong camra is used.

Is there any solution for this?

**Comment by ericblade** [comment]
Yep.  Such as most LG phones since at least the G6, I think a bit earlier than that, you have multiple rear cameras, one of which is usually a wide-angle, and totally fisheyes whatever it is that you're looking at, which becomes unscannable with Quagga.   (maybe someone could implement an anti-fisheye effect...)

You can use Quagga.CameraAccess.enumerateVideoDevices() to get a list of all the camera devices and allow for the user to select which one to use, based on it's deviceId.  Then you can pass the deviceId into Quagga.init instead of the 'facing' property, and it will use the given device.  I believe this is in the examples in the repo, also

**Comment by berberon** [comment]
Is there an example of how to use Quagga.CameraAccess.enumerateDevices()?

**Comment by ericblade** [comment]
It works exactly the same way as the built-in [enumerateDevices](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) but filters out everything that isn't a video input device.  
(i just realized it's "Quagga.CameraAccess.enumerateVideoDevices" and updated my first comment)

Here's the test for CameraAccess.enumerateVideoDevices in my fork https://github.com/ericblade/quagga2/blob/0e7228e29793d132f8f78debcb455b369ed798ad/src/input/test/browser/camera_access.spec.ts#L31

and here's the example from the example folder in the source https://github.com/ericblade/quagga2/blob/master/example/live_w_locator.js#L85

**Comment by berberon** [comment]
I’m sorry for the novice question but I can’t debug this on my PC and nothing happens on my mobile (where I have no idea how to debug).

Is there any way to allow something like Dev Tools on an Iphone or Android?

**Comment by ericblade** [comment]
On a PC, you can serve from localhost, and Chrome will let you use the Camera APIs if you're connecting to localhost.  You can also run Web Inspector in Chrome on your desktop, and attach it to your Android phone.  

Remote debugging Android: https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by berberon** [comment]
thanks Eric, i appreciate your response.

tried for several hours today to get dev tools and my android to work. made
very little progress as this is not my strong side :)

if anyone is interested, i’ll be more than happy to pay for the fix i need.

i can be contacted at berber@weber-sites.com

thanks
