### ISSUE TITLE
doing a scan, ean is being interpreted as upc_e

### ISSUE THREAD

**Issue by madmanpierre** [serratus/quaggaJS#48]
The addition of the format was a great help in determining some scan errors I'm getting. Specifically,  I'm getting some of my ean barcodes interpreted as upc_e.

Is there a way I can get 'the image' that was used for processing back without going into debug? (If the answer is 'no, use debug' then I'll work on understanding that tomorrow. But if there is a way I can get the image that was used for the onDetected - then I'll use that (and it will allow me to have my customers send me 'faulty reads' as well, I'll write the code to allow them to email me any 'bad reads' along with the result data object.)

**Comment by madmanpierre** [comment]
I probably mention ... I have tried grabbing the 'current' image from the getMediaStream as soon as I start the onDetected callback, but the image has changed too much by that time, because when I save it and then pass it to decodeSingle, I get a different result. Too much movement in my hand holding the barcoded product by the time I get the callback. I believe these bad reads are happening while I'm in the process of bringing the barcode into focus, but before they are fully in focus, and based on shadows, I think it may be that 'part' of the barcode is in focus. But I can't tell for sure since I don't know the exact image that was being processed.

**Comment by madmanpierre** [comment]
I am finding that the upc_e_reader is the most 'aggressive' reading barcodes that don't belong to it. I was working today on writing checksum calculation routines to validate so I didn't yet try further to try to grab the images that are being read wrong. But my end of day testing was interesting: I had a couple EAN-8 codes I was trying to read. When upc_e_reader was excluded from the list - the codes were 'unreadable' (I couldn't get EAN-8 to recognize it), but when I added upc_e_reader back in - it would read them and give me an 8 character string back that was correct for an EAN-8 (including the EAN check digit). Of course, my validation routine rejected it since you can't have 8 digits for an upc_e (since upc_e is 6 characters including the checkdigit).

The attached image was caught from the stream a fraction of a second after I got an upc_e reading of this EAN-8 code.
![ean-8](https://cloud.githubusercontent.com/assets/3065555/8199820/c06a9f08-1478-11e5-8eef-d1bd6420f395.png)

**Comment by serratus** [comment]
Thanks for the input. Actually, that's a big issue for me too. During "debugging" sessions, I also tried to get the most recent image by simply grabbing the buffer from the `<canvas>` but that was usually too late. The best way is to print the internal buffer, which is used for localizing and decoding, on to a canvas and create an image from that. The only downside here is, that you lose the color information of the image. I would definitely go for this approach, simply because it's overly useful. Hopefully I can find some time on the weekend to make some progress on that.

**Comment by madmanpierre** [comment]
OK. I'll pursue other directions and see where you get on that - I'm glad to know that you were have the same problems that I have been having - I'm not going the wrong direction :)

**Comment by serratus** [comment]
I've just added a [ResultCollector](https://github.com/serratus/quaggaJS#resultcollector) making it easier to keep track of false-positive results. You can also take a look at the adapted [example](https://github.com/serratus/quaggaJS/blob/master/example/live_w_locator.js#L2) to see how it works. Please make sure to turn on the ``inputStream.singleChannel`` flag for ``Quagga.decodeSingle`` when comparing the results.

**Comment by madmanpierre** [comment]
I'll add the new properties to the typescript .d.ts file tonight or tomorrow. They will be in the next merge. If someone needs it sooner than that, email me and I'll send it to you.

**Comment by serratus** [comment]
I've just pushed my latest changes to the master branch (see 31df5d8faff10325b0f94cdd28f4e990eb38fc08). They include various fixes and tweaks for the entire EAN and UPC familiy. From now on, the misinterpretation of the shorter codes (e.g.: upc-e instead of upc) should occur far less frequent.

One more thought on the configuration working with more than one type of barcode: Make sure to include them in the right order, because UPC codes might otherwise be interpreted as EAN-13 codes, since the only differentiation is the leading 0. 

```javascript
decoder: {
  readers : ["upc_reader", "ean_reader", "upc_e_reader", "ean_8_reader"]
},
```

**Comment by serratus** [comment]
I hope the latest version suits your needs and works better than before. Could you please review and then close the issue if no longer needed? Thanks!

**Comment by madmanpierre** [comment]
I have not had a false positive since the new changes. I hadn't specifically tested for it (busy with our beta) - so I just spent 20 minutes. And while I used to be able to generate 5-20 per minute, I couldn't produce even one false positive in 20 minutes. I'll try with more barcodes over the next week, but I agree, this issue is closed.
