### ISSUE TITLE
Request for I2of5 Support

### ISSUE THREAD

**Issue by swinterstein** [serratus/quaggaJS#49]
It would be great if QuaggaJS would support the I2of5 ("Interleaved 2 of 5") format.

A general description of the format symbology is here: http://www.barcodeisland.com/int2of5.phtml

As I understand it, I2of5 is only a "symbology", so here are some actual sample images of labels used in our project:

![i2of5-1](https://cloud.githubusercontent.com/assets/12640508/8451543/5776c0cc-1fe4-11e5-8b60-45a53b7ce95c.jpg)
![i2of5-2](https://cloud.githubusercontent.com/assets/12640508/8451547/6276030c-1fe4-11e5-9c4f-278283f9a08d.jpg)
![i2of5-3](https://cloud.githubusercontent.com/assets/12640508/8451552/690af060-1fe4-11e5-8479-3a74912032cf.jpg)
![i2of5-0](https://cloud.githubusercontent.com/assets/12640508/8451524/3282326a-1fe4-11e5-8a72-ac4101f38ad3.jpg)

**Comment by serratus** [comment]
Thanks for the resources. They are going to be of much help during the implementation. I'll start with the implementation in the next few days. I'll keep you posted!

**Comment by serratus** [comment]
During the implementation, I tried to test your sample-images and noticed the following issues:
- The barcodes are really dense (more than 20 characters)
- Localization is difficult because of the density (higher resolution needed)
- Black bars are *bleeding* into white spaces
- Narrow bars and spaces should have roughly the same size, but the black bars are, in extreme cases, 5 times wider than their respective whitespace

Currently, I don't exactly know how to get around some of these limitations/issues. If you are only using I2of5 barcodes, without any other readers enabled, this could also help.

**Comment by swinterstein** [comment]
Thanks Christoph for your efforts. Although it seems that our device (Thinkpad 10) is not really up to the task, I do hope the I2of5 implementation will be of use for other people.

**Comment by serratus** [comment]
Thanks for the feedback. Primarily, it seems the issues are caused by the localization module which is not really capable of finding high density codes. I'll give it another try without localization, and report back to you.
