### ISSUE TITLE
iOS Compatibility via PhoneGap

### ISSUE THREAD

**Issue by Shagans982** [serratus/quaggaJS#51]
Hi Serratus, 

This may have already been covered and if so, my apologies. I just haven't been able to locate much on it. Im aware that Safari does not user the getUserMedia API and it is my understanding that the cordova media plugins for photo & video capture will not work. Is there any other method of getting this to run in iOS?

**Comment by serratus** [comment]
Hi Stephen,

this topic was once discussed in #27 but no definite solution was presented. Since I do not have any iOS devices in my possession, the priority is quite on the low side. All the research I have been conducting was not fruitful to date. My guess is, that you are looking for live-decoding, right? Image-snapping and decoding is no problem at all.

**Comment by Shagans982** [comment]
Correct, yes. I did see this mentioned in thread 27. I Wasn't sure if this was the entirety of the information on the topic but live decoding is what I was inquiring about. Thank you for the reply.
