### ISSUE TITLE
Internet Explorer supported?

### ISSUE THREAD

**Issue by tyrex1975** [serratus/quaggaJS#53]
Sorry for the dumb-ass question, but I can't make any of the QuaggaJS examples work in any version of IE. I've tried IE11/10 in Windows 8.1 & IE on Windows Phone 8.1.

All of these browsers support the File API and Canvas, so I figured the images should be getting into Quagga, just no further?

**Comment by serratus** [comment]
I haven't paid any attention to IE so far, but I was curious enough to try after your question. And indeed, it did not work for me either (IE11). There is no visible error in the console, nor any other indication why it should not work. First off, turning off the web-workers got me one step further where the debugger finally stopped at an unhandled exception. The problem in IE <= 11 is, that it does not support `Math.imul` (see [here](https://msdn.microsoft.com/library/dn858242%28v=vs.94%29.aspx)) out of the box. This must be solved using a [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul), which you can include yourself if you want.

If I find more time, I'll continue digging around in the IE case. But it is not high on my priority list, simply because most of the awesome features are going to be included in Microsoft Edge anyway :smiley:

**Comment by tyrex1975** [comment]
Thank you - that's helpful. My reason for asking is that we're working on an implementation of QuaggaJS that we're hoping we can make work in a web app on mobile devices - this necessitates operation on at least iOS, Android and Windows Phone.

Performance isn't too much of an issue because we're unlikely to be using getUserMedia at the moment due to lack of cross-browser support, so I'll take a look at the polyfill and see if we can get it to work.

**Comment by IanYates** [comment]
@tyrex1975 - any luck with this?  I'm about to try the same.  I was debugging a prettified version of the minimised JS in the examples and figured I should check the issues list instead :)  I'll probably get around to trying this in the next few days and will report back if you don't first.

**Comment by tyrex1975** [comment]
Hi Ian - yes the Math.imul polyfill described in Serratus' post pretty much does the trick, that should be all you need.

**Comment by IanYates** [comment]
Thanks - that's great to hear :+1:

**Comment by serratus** [comment]
With the newest update of quagga (e5acf19e08c34ef4c63d95061810bc7781f2108e), the `Math.imul` polyfill is now included in the package. So, there is no need for any additional code to work within IE browsers. I've also fixed the problem with web-workers, making it safe to use with any number of workers.

**Comment by KarthikDP** [comment]
@Serratus: am just looking into the new update of quagga, still am facing issue while using IE browser, error: SCRIPT5022: SecurityError, HTML7007: One or more blob URLs were revoked by closing the blob for which they were created. These URLs will no longer resolve as the data backing the URL has been freed.

**Comment by serratus** [comment]
@KarthikDP Which versions (IE and Quagga) did you try?
