### ISSUE TITLE
EAN with Ean-5 Supplement

### ISSUE THREAD

**Issue by bjonsonSTG** [serratus/quaggaJS#71]
![capture](https://cloud.githubusercontent.com/assets/8097056/10475220/bf001c4e-71f5-11e5-9eb0-093950accf69.PNG)
The bounding box drawn in the examples, when scanning for EAN+EAN5 supplement (like on the ISBN code on the back of books) includes the 13 digit EAN code as well as the 5 digit supplement, but the returned code is only for the 13 digits.  Is there a way to get the 5 digit supplement as well?

**Comment by serratus** [comment]
This part is not yet implemented. The difficulty lies also in the nature of the separation of these two codes. The barcode-locator feature usually sees these two as separate barcodes, depending on the image conditions. I'll look into that, but since I haven't done any research on this, it might take a while.

**Comment by bjonsonSTG** [comment]
Thanks!  I thought so ...

**Comment by serratus** [comment]
Finally, this feature made it to Quagga. See https://github.com/serratus/quaggaJS/releases/tag/v0.11.0
