### ISSUE TITLE
Quagga.decodeSingle() function hanging on mobile.

### ISSUE THREAD

**Issue by pouta** [serratus/quaggaJS#75]
I have the following code:
```
var self = this,
config = $.extend({}, self.state, {src: src});
$(".mdl-card__supporting-text").text("ahsdvasd3");
Quagga.decodeSingle(config, function(result) {
    $(".mdl-card__supporting-text").text("ahsdvasd4");
```
The following code is not relevant...

The text never gets changed to "ahsdvasd4" on mobile but with no problems on desktop since it changes text and sucessfully decodes the image.

Sorry for the bad english.
Thanks in advance

**Comment by pouta** [comment]
By the way. This works on mobile version of chrome but not firefox...

**Comment by serratus** [comment]
Recently, I've noticed some differences between Chrome and Firefox as well. Some barcodes are being recognized on Firefox, but not on Chrome, and vice-versa. This only happens if you have an identical image. If you use a web-cam, this should not be an issue.

Can you maybe attach the image you are trying to decode? I'll take a look into that. But as I said, the minor differences in JavaScript execution between Firefox and Chrome (Number formatting, etc.) might play a role here.

**Comment by serratus** [comment]
Please reopen this issue whenever you have more information at hand, like type of mobile phone and versions of Firefox/Chrome used. Thanks
