### ISSUE TITLE
Live Example Failing iOS 9.1

### ISSUE THREAD

**Issue by garyns** [serratus/quaggaJS#81]
Hi,

I cannot get the live example to work oh my iPhone 6 / iOS 9.1. I get the same problem in Safari and Chrome.

Any suggestions? Neither browser is asking for access to the camera, and I've checked the settings and found nothing helpful.

![img_5545](https://cloud.githubusercontent.com/assets/497167/11704430/d738a74a-9f3b-11e5-8436-59a8c67c3359.PNG)

Thanks
Gary.

**Comment by RobertoAlca** [comment]
with firefox?

**Comment by garyns** [comment]
Just downloaded and tried ff. Same problem. 
Gary.

**Comment by serratus** [comment]
As stated in the readme, `getUserMedia` is not supported under iOS. Regardless which browser you are using, due to the restriction of Apple requiring all web-browsers to use their built-in WebKit browser engine (Layout & JavaScript). See [Apple Guidelines 2.17](https://developer.apple.com/app-store/review/guidelines/)
