### ISSUE TITLE
Can not detect isbn? 

### ISSUE THREAD

**Issue by DengZuoheng** [serratus/quaggaJS#92]
I tried this https://zh.wikipedia.org/wiki/%E5%9B%BD%E9%99%85%E6%A0%87%E5%87%86%E4%B9%A6%E5%8F%B7#/media/File:ISBN.gif

it seems not deteced

**Comment by stelt** [comment]
it CAN detect ISBN, which is a subset of EAN (so that is the option you have to choose).
It's very close to NOT working for the machine/browser combinations I've tried. Seemed that only with perfect lighting, perfect webcam, holding the book almost perfectly still, then there is a small chance it might actually detect the thing.
But maybe that's just me.

**Comment by serratus** [comment]
Well, thanks for the feedback. Like @stelt has already mentioned, the regular ISBN (without extension) is simply an EAN code. But unfortunately, the ISBN codes on books are usually very small and hard to capture. Having well-working auto-focus and good lighting usually helps. I'll try to improve the results even further, but the browser APIs don't give a lot of freedom in terms of triggering auto-focus or adjusting white-balance.

The problem with not detecting your example barcode is most probably because of the low resolution. If you give it a try with a better image it should work out of the box.

<img width="682" alt="isbn-reading" src="https://cloud.githubusercontent.com/assets/1381822/13906691/453168c2-eedd-11e5-9d6a-15ce21ac3141.png">

**Comment by stelt** [comment]
On my Fairphone 2 with Chrome browser it works pretty fast even.
On a fairphone 1 it was OK.
Many other devices failed, mostly for bad cam, quite a few for not allowing webcam use, or the user not understanding that or not knowing how to fix that.
