### ISSUE TITLE
Get binarized image

### ISSUE THREAD

**Issue by JauernigIT** [serratus/quaggaJS#96]
Short question: is it currently possible (how?) to get the current binarized image (Otsu) inside of the `Quagga.onProcessed()` callback? In my use case, after Quagga is done, I'm activating a second QR code scanning library and thus to use the binarized image would be really great.

**Comment by serratus** [comment]
Unfortunately, that's not easily possible due to the use of web-workers. The image-data is always held in a buffer which is passed back and forth between the UI and the worker. This data-passing invalidates the access to the buffer when it's used within the web-worker. The only chance I see is to pause the execution of quagga, and then activate the QR scanning library.

BTW, which library are you using for QR code scanning? Maybe I there is an easy way to create some kind of plugin. I was planning on implementing a QR code scanner, but time is currently too precious :laughing:

**Comment by JauernigIT** [comment]
I'm using [jsqrcode](https://github.com/LazarSoft/jsqrcode), a javascript port of the QR part from [zxing](https://github.com/zxing/zxing). I've not found a better library for javascript QR code scanning.

My solution with the combined Quagga/QR scanning is actually working, but it would have been great to use the binarized Quagga image. At the moment I'm using `Quagga.canvas.dom.image` to get the input data for jsqrcode.

**Comment by JauernigIT** [comment]
For debugging purposes: is there some easy way to output the Otsu-binarized image to a canvas on the screen?

**Comment by serratus** [comment]
Yes, there is, but only in development mode. Make sure to not use web-workers, since they don't have access to the DOM. You can output the binarized image by setting `locator.debug.showCanvas` to `true` and make sure you have an HTML element present with an id `debug`.

Unfortunately, due to a spelling error, the canvas is not printed. In the meantime, as a workaround, please set the following in your config (note the duplication of `showCanvas`):

```javascript
{
locator: {
    showCanvas: true,
    debug: {
      showCanvas: true
    }
}
```

**Comment by JauernigIT** [comment]
Thanks, this works!
